DROP TABLE IF EXISTS atributo CASCADE;
DROP TABLE IF EXISTS estado_acta CASCADE;
DROP TABLE IF EXISTS estado_activo CASCADE;
DROP TABLE IF EXISTS tipo_activo CASCADE;
DROP TABLE IF EXISTS tipo_servicio CASCADE;
DROP TABLE IF EXISTS acta_entrega CASCADE;
DROP TABLE IF EXISTS atributo_tipoactivo CASCADE;
DROP TABLE IF EXISTS etiqueta CASCADE;
DROP TABLE IF EXISTS subestado_activo CASCADE;
DROP TABLE IF EXISTS observacion CASCADE;
DROP TABLE IF EXISTS movimiento CASCADE;
DROP TABLE IF EXISTS atributo_activo CASCADE;
DROP TABLE IF EXISTS activo_actaentrega CASCADE;
DROP TABLE IF EXISTS activo CASCADE;
DROP TABLE IF EXISTS clients CASCADE;


CREATE TABLE clients ( 
    id int8 GENERATED BY DEFAULT AS IDENTITY( 
        MINVALUE 0 
        NO MAXVALUE 
        START 0 
        NO CYCLE
    ) NOT NULL, 
    client_code varchar(255) NOT NULL, 
    "name" varchar(255) NOT NULL, 
    CONSTRAINT clients_pkey PRIMARY KEY (id)
);

CREATE TABLE atributo (
    atributo_id int4 GENERATED BY DEFAULT AS IDENTITY( 
        INCREMENT BY 1 
        MINVALUE 1 
        MAXVALUE 2147483647 
        START 1 
        CACHE 1 
        NO CYCLE
    ) NOT NULL, 
    nombre varchar(100) NOT NULL, 
    tiene_valores_validos bool NOT NULL, 
    tipo_dato varchar(50) NOT NULL, 
    valores_validos jsonb NULL, 
    CONSTRAINT atributo_pkey PRIMARY KEY (atributo_id)
);


CREATE TABLE estado_acta (
    estado_acta varchar(100) NOT NULL, 
    CONSTRAINT estado_acta_pkey PRIMARY KEY (estado_acta)
);


CREATE TABLE estado_activo ( 
    estado varchar(100) NOT NULL, 
    CONSTRAINT estado_activo_pkey PRIMARY KEY (estado)
);


CREATE TABLE tipo_activo ( 
    tipo_activo varchar(100) NOT NULL, 
    marcas_y_modelos jsonb NULL, 
    CONSTRAINT tipo_activo_pkey PRIMARY KEY (tipo_activo)
);


CREATE TABLE tipo_servicio ( 
    servicio varchar(100) NOT NULL, 
    prefijo varchar(5) NOT NULL, 
    CONSTRAINT tipo_servicio_pkey PRIMARY KEY (servicio)
);


CREATE TABLE acta_entrega (
    actaentrega_id varchar(100) NOT NULL,
    campos_extra jsonb NULL,
    documento_firmado_url text NULL,
    fecha_fin date NULL,
    fecha_inicio date NULL,
    renovaciones int4 DEFAULT 0 NOT NULL,
    cliente_id int8 NULL,
    estado varchar(100) NOT NULL,
    tipo_servicio varchar(100) NOT NULL,
    meses_arrendamiento int4 DEFAULT 0 NOT NULL,
    CONSTRAINT pk_acta_entrega PRIMARY KEY (actaentrega_id),
    CONSTRAINT fk_acta_entrega__estado__estado_acta FOREIGN KEY (estado) REFERENCES estado_acta(estado_acta),
    CONSTRAINT fk_acta_entrega__cliente_id__clients FOREIGN KEY (cliente_id) REFERENCES clients(id),
    CONSTRAINT fk_acta_entrega__tipo_servicio__tipo_servicio FOREIGN KEY (tipo_servicio) REFERENCES tipo_servicio(servicio)
);


CREATE TABLE atributo_tipoactivo (
    atributo_id int4 NOT NULL,
    tipo_activo varchar(255) NOT NULL,
    CONSTRAINT pk_atributo_tipoactivo 
        PRIMARY KEY (atributo_id, tipo_activo),
    CONSTRAINT fk_atributo_tipoactivo__atributo_id__atributo 
        FOREIGN KEY (atributo_id) REFERENCES atributo(atributo_id) ON DELETE CASCADE,
    CONSTRAINT fk_atributo_tipoactivo__tipo_activo__tipo_activo 
        FOREIGN KEY (tipo_activo) REFERENCES tipo_activo(tipo_activo) ON DELETE CASCADE
);



CREATE TABLE etiqueta (
    etiqueta_id int8 GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT BY 1 
        MINVALUE 1 
        MAXVALUE 9223372036854775807 
        START 1 
        CACHE 1 
        NO CYCLE
    ) NOT NULL,
    canon numeric(38, 2) NULL,
    is_enabled bool NOT NULL,
    nombre text NOT NULL,
    acta_asociada varchar(100) NOT NULL,
    CONSTRAINT pk_etiqueta 
        PRIMARY KEY (etiqueta_id),
    CONSTRAINT fk_etiqueta__acta_asociada__acta_entrega 
        FOREIGN KEY (acta_asociada) REFERENCES acta_entrega(actaentrega_id) ON DELETE CASCADE
);



CREATE TABLE subestado_activo (
    subestado varchar(100) NOT NULL,
    estado_padre varchar(100) NULL,
    CONSTRAINT pk_subestado_activo 
        PRIMARY KEY (subestado),
    CONSTRAINT fk_subestado_activo__estado_padre__estado_activo 
        FOREIGN KEY (estado_padre) REFERENCES estado_activo(estado) ON DELETE SET NULL
);


CREATE TABLE activo (
    activo_id int8 GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT BY 1 
        MINVALUE 1 
        MAXVALUE 9223372036854775807 
        START 1 
        CACHE 1 
        NO CYCLE
    ) NOT NULL,
    acta_entrega_actual text NULL,
    asignado_a varchar(100) NULL,
    condicion text NULL,
    factura_compra varchar(100) NULL,
    fecha_compra date NULL,
    garantia text NULL,
    marca varchar(100) NOT NULL,
    modelo varchar(100) NOT NULL,
    proveedor varchar(100) NULL,
    ubicacion text NULL,
    estado varchar(100) NULL,
    subestado varchar(100) NOT NULL,
    tipo varchar(100) NOT NULL,
    CONSTRAINT pk_activo 
        PRIMARY KEY (activo_id),
    CONSTRAINT fk_activo__estado__estado_activo 
        FOREIGN KEY (estado) REFERENCES estado_activo(estado),
    CONSTRAINT fk_activo__tipo__tipo_activo 
        FOREIGN KEY (tipo) REFERENCES tipo_activo(tipo_activo),
    CONSTRAINT fk_activo__subestado__subestado_activo 
        FOREIGN KEY (subestado) REFERENCES subestado_activo(subestado)
);



CREATE TABLE activo_actaentrega (
    asignado_a varchar(100) NULL,
    descripcion text NULL,
    actaentrega_id varchar(255) NOT NULL,
    activo_id int8 NOT NULL,
    etiqueta_asociada int8 NULL,
    CONSTRAINT pk_activo_actaentrega 
        PRIMARY KEY (actaentrega_id, activo_id),
    CONSTRAINT fk_activo_actaentrega__actaentrega_id__acta_entrega 
        FOREIGN KEY (actaentrega_id) REFERENCES acta_entrega(actaentrega_id) ON DELETE CASCADE,
    CONSTRAINT fk_activo_actaentrega__activo_id__activo 
        FOREIGN KEY (activo_id) REFERENCES activo(activo_id) ON DELETE CASCADE,
    CONSTRAINT fk_activo_actaentrega__etiqueta_asociada__etiqueta 
        FOREIGN KEY (etiqueta_asociada) REFERENCES etiqueta(etiqueta_id) ON DELETE CASCADE
);



CREATE TABLE atributo_activo (
    valor text NOT NULL,
    activo_id int8 NOT NULL,
    atributo_id int4 NOT NULL,
    CONSTRAINT pk_atributo_activo 
        PRIMARY KEY (activo_id, atributo_id),
    CONSTRAINT fk_atributo_activo__atributo_id__atributo 
        FOREIGN KEY (atributo_id) REFERENCES atributo(atributo_id) ON DELETE CASCADE,
    CONSTRAINT fk_atributo_activo__activo_id__activo 
        FOREIGN KEY (activo_id) REFERENCES activo(activo_id) ON DELETE CASCADE
);



CREATE TABLE movimiento (
    movimiento_id int8 GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT BY 1 
        MINVALUE 1 
        MAXVALUE 9223372036854775807 
        START 1 
        CACHE 1 
        NO CYCLE
    ) NOT NULL,
    contenido text NOT NULL,
    fecha timestamp(6) NOT NULL,
    activo_id int8 NOT NULL,
    CONSTRAINT pk_movimiento 
        PRIMARY KEY (movimiento_id),
    CONSTRAINT fk_movimiento__activo_id__activo 
        FOREIGN KEY (activo_id) REFERENCES activo(activo_id) ON DELETE CASCADE
);



CREATE TABLE observacion (
    observacion_id int8 GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT BY 1 
        MINVALUE 1 
        MAXVALUE 9223372036854775807 
        START 1 
        CACHE 1 
        NO CYCLE
    ) NOT NULL,
    contenido text NOT NULL,
    fecha timestamp(6) NOT NULL,
    activo_id int8 NOT NULL,
    CONSTRAINT pk_observacion 
        PRIMARY KEY (observacion_id),
    CONSTRAINT fk_observacion__activo_id__activo 
        FOREIGN KEY (activo_id) REFERENCES activo(activo_id) ON DELETE CASCADE
);


DROP FUNCTION IF EXISTS normalize_key(text);

CREATE OR REPLACE FUNCTION normalize_key(txt text)
RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
  SELECT btrim(
           regexp_replace(
             lower(coalesce(txt,'')),
             '[^a-z0-9]+', '_', 'g'   -- espacios, guiones, etc. -> '_'
           ),
           '_'                         -- quita '_' al inicio/fin
         )
$$;
